version: "3"
services:
  # forum-server:
  #   build: .
  #   container_name: node-server-1
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   command: npm run start

  cache:
    image: redis:7.2-rc3
    restart: always
    ports:
      - "19736:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
