version: "3"
services:
  forum-server:
    build: .
    container_name: node-server-1
    ports:
      - "3000:3000"
    restart: always 
    environment: 
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - GITHUB_REDIRECT_URI=
    command: npm run start 
