name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'master'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: checkout
        uses: actions/checkout@v2

      - name: format
        run: |
          - cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: build
        run: |
          cargo build
          cargo test

  containeraized:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: authentication
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: container_meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
            
      - name: push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
